version: '3.5'
services:
    csgo:
        image: cm2network/csgo:latest
        container_name: csgoserver
        restart: always
        env_file:
            - .env
        tty: true
        environment:
            SRCDS_RCONPW: "$SRCDS_RCONPW"
            SRCDS_PW: "$SRCDS_PW"
            SRCDS_PORT: "$SRCDS_PORT:27015"
            SRCDS_TV_PORT: "$SRCDS_TV_PORT:27020"
            SRCDS_FPSMAX: "$SRCDS_FPSMAX:300"
            SRCDS_TICKRATE: "$SRCDS_TICKRATE:128"
            SRCDS_MAXPLAYERS: "$SRCDS_MAXPLAYERS:14"
            SRCDS_STARTMAP: "$SRCDS_STARTMAP:de_dust2"
            SRCDS_REGION: "$SRCDS_REGION:3"
            SRCDS_MAPGROUP: "$SRCDS_MAPGROUP:mg_active"
        ports:
            - target: "$PORT"
              published: "$PORT"
              protocol: udp
            - target: "$PORT"
              published: "$PORT"
              protocol: tcp
        volumes:
            - ./cfg/:/home/steam/csgo-dedicated/csgo/cfg/